### ISSUE TITLE
[Feature Request / Function Query] Ignore specific libraries

### ISSUE THREAD

**Issue by Pantar2205** [clara-j/media_cleaner#10]
Hello & Thank you for this script.

/media/shows/shows-auto-delete
/media/shows/shows-keep-forever

these are my actual directory names and same naming system for movies.

is it possible to get this script to either whitelist/blacklist the corresponding folders?

**Comment by terrelsa13** [comment]
I do not see a quick and easy way to implement this. And this is what the favourite functionality is for?

Mark all of the series', seasons, and/or episodes in the .../shows-keep-forever/ directory as favourite in emby/jellyfin. Then in the config file set `keep_favorites_episode=1`. When the script runs these series', seasons, and/or episodes will be excluded from deletion.

Do the same in your ../movies-keep-forever/ directory and `keep_favorites_episode=1`.

**Comment by terrelsa13** [comment]
@Pantar2205 finally got around to implementing this feature request. Please [check it out here](https://github.com/terrelsa13/media_cleaner).

Let me know if there is any feedback.

**Comment by terrelsa13** [comment]
#16

**Comment by Pantar2205** [comment]
Phenomenal!! I won't be able to test this for some time as I have just begun the process of re doing my entire setup from scratch. Thank you so much, this is invaluable to me. I really appreciate your work. I will close this and re-open if needs be.
