### ISSUE TITLE
Jellyfin 10.7 - New database structure

### ISSUE THREAD

**Issue by AussieAbroad** [clara-j/media_cleaner#14]
Are you planning to update this due to changes with Jellyfin 10.7 media database

**Comment by zilexa** [comment]
Thanks for the email @AussieAbroad 
As I am no Python dev we rely on @clara-j or perhaps @terrelsa13 to make it compatible with the new db..

**Comment by terrelsa13** [comment]
@AussieAbroad and @zilexa When I have the time, I will have to look into this a little more.

**Comment by AussieAbroad** [comment]
https://github.com/jellyfin/jellyfin/releases/tag/v10.7.0-rc3
This is the GITHUB link for RC3

**Comment by terrelsa13** [comment]
@AussieAbroad @zilexa I have been playing around with this for the past few days. The API seems to change or break when I go from 10.6.x to 10.7.0. I have tried every thing I can think of to get the jellyfin API to play nicely.

[Posted on the jellyfin support forum](https://forum.jellyfin.org/t/did-the-api-change-for-users-authenticatebyname/4329) a few days ago in hopes someone with more knowledge about the jellyfin API would help connect the dots on what I am missing. No replies as of yet.

**Comment by AussieAbroad** [comment]
With 10.7 officially out now, does creating a unique API key through Jellyfin settings and using this for this application make a difference?

**Comment by terrelsa13** [comment]
@AussieAbroad Assuming no other API functionality has changed; then yes. Manually creating an API key would work.

**Have not had a chance to try this yet. But you can by...**
1. Commenting out the line: auth_key=get_auth_key(server_url, username, password, password_sha1)
2. Make a line underneath it: auth_key='Your_Manually_Created_API_Key'

FYI - The jellyfin forums are being closed and archived. Re-posted [the request for help](https://www.reddit.com/r/jellyfin/comments/m4x9lz/1070_api_help_with_usersauthenticatebyname/) with this API issue on reddit as they suggest is a more active community. Hoping asking the question in the more active community will get it some attention.

**Comment by terrelsa13** [comment]
@AussieAbroad @zilexa  Got this working again for jellyfin. Looks like the same API call will also work for emby. Need to do some testing and then I will post my update. I will likely have time later this week.

**Comment by terrelsa13** [comment]
@zilexa @AussieAbroad  Try the changes on [my fork](https://github.com/terrelsa13/media_cleaner); this should work with emby and jellfyin 10.7.0.

**Comment by AussieAbroad** [comment]
@terrelsa13  Thank you so much for sharing, I will test this weekend with Jellyfin and let you know.

**Comment by terrelsa13** [comment]
#12

**Comment by AussieAbroad** [comment]
Thank you @terrelsa13 . I installed this on Sunday night and ran for 2 nights. All seems to be working well with Jellyfin 10.7.1. Fantastic job in fixing the API, this is a huge help in managing my disk space. This issue for Jellyfin is closed
