### ISSUE TITLE
terrelsa13 trying to use your latest commit on the fork without luck

### ISSUE THREAD

**Issue by EdeAbreu23** [clara-j/media_cleaner#17]
Hello, so i was pulling your latest changes from the fork and the configuration goes correctly and it detects my list of users and list of media folders but when running it nothing will show up..

with your latest fork:
![image](https://user-images.githubusercontent.com/7027367/113476604-67970600-9474-11eb-8008-a44d5c63ef50.png)

with an older fork:
![image](https://user-images.githubusercontent.com/7027367/113476619-84333e00-9474-11eb-92ef-376f27e70d9d.png)

**Comment by terrelsa13** [comment]
@elvis0288 Hey! Yeah, I made some changes to the default config file. All of the ``` not_played_age_X=-1 ``` by default. So no media is checked. For example; if you want to delete Movies after ```31``` days and TV Episodes after ```14``` days, open the media_cleaner_config.py file in a text editor and change the values for the media types you want to "clean".

``` not_played_age_movies=31 ```
``` not_played_age_episode=14 ```
``` not_played_age_video=-1 ```
``` not played_age_trailer-1 ```
``` not played_age_audio=-1 ```

I guess I should put something in to check when all ``` not_played_age_X ``` config variables are set to ```-1``` and print a message on the screen to let the user know.

**Comment by terrelsa13** [comment]
@elvis0288 A message has been added to my latest fork to explain why nothing shows when all of the  ``` not_played_age_X=-1 ```.

**Comment by EdeAbreu23** [comment]
Excellent thank you for your work
