### ISSUE TITLE
issue when using your latest script

### ISSUE THREAD

**Issue by EdeAbreu23** [clara-j/media_cleaner#19]
Hello @terrelsa13 using the latest config will throw this error
![image](https://user-images.githubusercontent.com/7027367/117143087-55c4bd80-ada8-11eb-8134-2e3becc99715.png)

**Comment by EdeAbreu23** [comment]
![image](https://user-images.githubusercontent.com/7027367/117143782-19de2800-ada9-11eb-80f5-c517ea7edbba.png)
this is how it looks on the config

**Comment by elvis0288** [comment]
after doing some tests.. looks like this is the way it should look
![image](https://user-images.githubusercontent.com/7027367/117145149-b94fea80-adaa-11eb-86a5-03a59eedc690.png)

**Comment by terrelsa13** [comment]
@elvis0288 
On the surface this appears to be the same issue of having a single quote in your path name. I understand Windows and Linux allow the use of single quotes in a path name. But why is it necessary for your media library paths?

Find and replace the two instances of this...
`libfolders.replace('\'','\\\'')`

With This...
`libfolders.replace("'","\'")`

\
If that works, I will update the script.

**Comment by EdeAbreu23** [comment]
that did not work but i am actually changing all my folder names so it will not have that ' anymore

Thanks!

**Comment by EdeAbreu23** [comment]
so i download you latest script and remove all the ' from my folders but i am getting an error when running the script after the configuration
![image](https://user-images.githubusercontent.com/7027367/117285118-8ddb0780-ae5f-11eb-9f2a-2e710a22b170.png)

**Comment by terrelsa13** [comment]
Backslash is the escape character in python.

I do not have a windows. So I am able to set up an emby/jellyfin server to test this. Will you try two possible solutions for me?...

Open your config file...
1. Find the user_bl_libs and/or user_wl_libs variable
2. Replace all single backslashes with double backslashes. So from this `"\"` to this `"\\"`. Try running the script like this.
3. Make sure remove_files=0

Then re-open your config file...

1. Again, fnd the user_bl_libs and/or user_wl_libs variable
2. Replace all double backslashes with single forward slashes. So from `"\\"` to this `"/"`. Try running the script like this.
3. Make sure remove_files=0

Which of these works?

**Comment by terrelsa13** [comment]
@elvis0288 
Will you also send a screenshot of the FULL paths shown when the script is run for the first time and blacklist and/or whitelists are being selected for a user?

**Comment by EdeAbreu23** [comment]
this is how it shows
![image](https://user-images.githubusercontent.com/7027367/117365947-fbb31d80-aeb7-11eb-9125-a7104f2f84ab.png)
and this is how you have it on the config
![image](https://user-images.githubusercontent.com/7027367/117365993-0c639380-aeb8-11eb-87cb-56ec9f646e34.png)

**Comment by EdeAbreu23** [comment]
the first option was still giving the error.. the second option went through with the -1 of the media to delete but when i put 180 days it displayed a different error.
![image](https://user-images.githubusercontent.com/7027367/117366339-809e3700-aeb8-11eb-9316-6ea929778f50.png)

but if the error is not related then the correct way would be:
![image](https://user-images.githubusercontent.com/7027367/117366395-990e5180-aeb8-11eb-94c1-3e2f11ed645c.png)

**Comment by terrelsa13** [comment]
That last error `(KeyError: 'Size')` means the metadata item `['Size']` does not seem to exist for the episode it is currently making a keep/delete decision on. I added this check because I came across what appeared to be a placeholder media item that was created by the server before it was actually moved from its initial folder into where it will be located in the tv/movie/etc... folder structure. That can probably be fixed by checking if the metadata item exists before trying to use it. Then make to decision to use one, both, or none in this case.

**As for the paths issue:** I will need a little bit of time to get a Windows emby/jellyfin server up and running so I can try a few things out for handling Windows paths. I have to figure out how to store these Windows paths and then read them back out. What I do not know is if using the forward slash will still match paths when reading the config to deciding if the media item is blacklisted or whitelisted. For now, manually edit the config with forward slashes in the whitelist/blacklist.

[This branch](https://github.com/terrelsa13/media_cleaner/blob/MediaSourceTypeAndSizeCheckBeforeUse/media_cleaner.py) should get you past the `KeyError: 'Size'` issue.

**Comment by EdeAbreu23** [comment]
hello after using the new branch and the forward slash this happens
![image](https://user-images.githubusercontent.com/7027367/117379649-cf0b0000-aecf-11eb-8858-609b3034f1ec.png)

so it looks like no errors but nothing shows as watched and i do have a lot of items right now that has been watched

Thanks!

**Comment by terrelsa13** [comment]
> What I do not know is if using the forward slash will still match paths when reading the config to deciding if the media item is blacklisted or whitelisted.

Yeah, I mentioned that. When it is looking for a matching path "/" is not he same as "\\". So nothing is seen as needing to be deleted.

I will be able to fix this after I get a Windows emby/jellyfin server up and running.

**Comment by EdeAbreu23** [comment]
Hello @terrelsa13  any news on this?

Thanks!

**Comment by terrelsa13** [comment]
Try this [this branch](https://github.com/terrelsa13/media_cleaner/tree/MediaSourceTypeAndSizeCheckBeforeUse).

Let me know if this fixes the issue with handling paths in Windows.

I suggest creating a new configuration file.

**Comment by EdeAbreu23** [comment]
i am trying blacklist with the same result.. nothing is found
![image](https://user-images.githubusercontent.com/7027367/117894151-a3af5900-b2b3-11eb-864d-e78a6f7bb102.png)

**Comment by EdeAbreu23** [comment]
trying to use whitelist to see if that works but the config file cannot be created 
![image](https://user-images.githubusercontent.com/7027367/117894279-ec671200-b2b3-11eb-8aae-610b8b3ba842.png)

**Comment by EdeAbreu23** [comment]
actually blacklist also have this issue if i do not select another user.. so if i just pick 1 user it will show that error
![image](https://user-images.githubusercontent.com/7027367/117894432-3819bb80-b2b4-11eb-94ee-5e5949a5b873.png)

**Comment by EdeAbreu23** [comment]
actually it is happening in both if i do not select all my users.. so if i select just something other than my 6 users then it will throw that error

**Comment by EdeAbreu23** [comment]
ok sorry so many messages, i just tested whitelist and it is scanning and bringing back info
![image](https://user-images.githubusercontent.com/7027367/117894856-27b61080-b2b5-11eb-9be1-a140453e0e40.png)
so it looks like there is 2 issues. 
one is the blacklist not working correctly and
two is that if you do not add all users it will display an error and it will not create the config file

but it looks like at least on whitelist the path on windows is working now
Thanks!.

**Comment by terrelsa13** [comment]
> i am trying blacklist with the same result.. nothing is found
> ![image](https://user-images.githubusercontent.com/7027367/117894151-a3af5900-b2b3-11eb-864d-e78a6f7bb102.png)

For this, please read the "ATTENTION!!!" message and enable at least one media type to be monitored.

**Comment by terrelsa13** [comment]
I will have to look into the user selection issue.

**Comment by terrelsa13** [comment]
The user selection bug has been fixed and committed to the same link as above.

**Comment by EdeAbreu23** [comment]
it is working perfectly now thank you so much
