### ISSUE TITLE
Ability to whitelist/ignore series entirely?

### ISSUE THREAD

**Issue by vexersa** [clara-j/media_cleaner#20]
Great script, thanks!

Would it be possible/able to whitelist entire series/folders to prevent them being deleted? 

I've got some classic tv shows I'd like to keep, David Attenboroughs, etc. 

Thanks!

**Comment by EdeAbreu23** [comment]
Hello @vexersa you should be able to blacklist or whitelist from this [branch ](https://github.com/terrelsa13/media_cleaner)

**Comment by terrelsa13** [comment]
@vexersa Take a look at [this post](https://github.com/clara-j/media_cleaner/issues/15#issuecomment-776978024).

And as @elvis0288 mentions, you can also whitelist entire libraries.

**Comment by vexersa** [comment]
Thanks very much.
