### ISSUE TITLE
movies/shows not been deleted for multiple users

### ISSUE THREAD

**Issue by EdeAbreu23** [clara-j/media_cleaner#25]
Hello @terrelsa13  so i have my personal script which is running correctly and deleting everything as planned. but when i am running the other script we talked about in which we can delete from other users.. i am using blacklist as i do in my personal one but this one have 5 users and even though it shows 2 files have been deleted, it is not deleting it.. everytime i run it, it will continue to say those 2 files will be deleted..

any logs you would like to see? here is the script after it is run

[pastebin](https://pastebin.com/xDsPsYiR)

**Comment by terrelsa13** [comment]
@elvis0288 
`remove_files=0` needs to be changed to `remove_files=1` to delete media.

![Screenshot_2021-05-17 Start Cleaning media for server at http 127 0 0 1 8096 emby------------ - Pastebin com](https://user-images.githubusercontent.com/16886488/118513410-ad94ea00-b701-11eb-8f48-bb519966692f.png)

**Comment by EdeAbreu23** [comment]
Dumb me.. I should know this by now
