### ISSUE TITLE
Please add the item type "Book" (audio books)

### ISSUE THREAD

**Issue by WolfgangDpunkt** [clara-j/media_cleaner#28]
A wonderful tool that works very well for me, but unfortunately not for audio books.
I use Jellyfin to listen to my podcast collection, I would like to have already listened podcasts automatically deleted by the 
media_cleaner script.
The MP3 files of the podcasts are not recognized as "audio" (but the content type of the library is also Book and not Music).

Thank you very much!

This feature would perfectionize my user experience.

**Comment by terrelsa13** [comment]
@WolfgangDpunkt When I have the time, I will look into adding books.

**Comment by terrelsa13** [comment]
Looks like Emby and Jellyfin assign "Book" Library items different media types.

Emby --> audio
Jellyfin --> audioBook

@WolfgangDpunkt FYI - I have the basics in for the audioBook media type. Still need to add in the functionality to keep all child media items when an artist/author is set to favorite. Nothing checked in yet.
Unfortunately I am not seeing a metadata item for albumId/bookId so setting an album/book to favorite won't keep the child media items. Favorites will have to be set by artist/author or by specific audioBook media item.

**Comment by WolfgangDpunkt** [comment]
Thank you very much for your effort!

At least for podcasts, it is completely sufficient if only episodes with the favorite status can be protected.

Of course, the situation is different with real audiobooks, which consist of many individual files.

**Comment by terrelsa13** [comment]
@WolfgangDpunkt Try the branch at the link below. Should now work for the AudioBook media type. Let me know if it does what you are looking for. Once it does I will merge it into my master.

I recommend making a backup of your current script and configuration and running this in dry-run mode.

[https://github.com/terrelsa13/media_cleaner/tree/terrelsa13-Add-AudioBook-Media-Type](https://github.com/terrelsa13/media_cleaner/tree/terrelsa13-Add-AudioBook-Media-Type)

**Comment by WolfgangDpunkt** [comment]
This works wonderfully, just as it should!
My already listened podcast episodes are cleared successfully.

Thank you very much for this extremely useful script and the effort you put into updating it, which helps me a lot. This is very kind of you.

**Comment by terrelsa13** [comment]
Glad this does what you need it to do. Thank you for the feedback. And let me know if you find anything I may have missed or broken making this update.

The AudioBook media type has been merged into [my main.](https://github.com/terrelsa13/media_cleaner)

Please close this issue.
